language: python
python: 3.7
cache: pip
env:
  global:
    - REPO_NAME="${PWD##*/}"
    - PIPENV_IGNORE_VIRTUALENVS=1
    - SAM_CLI_TELEMETRY=0
    - LAMBDA_BUCKET="essentials-awss3lambdaartifactsbucket-x29ftznj6pqw"
    - CFN_BUCKET="bootstrap-awss3cloudformationbucket-19qromfd235z9"
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - mkdir -p ~/.aws
  - echo -e "[default]\nregion=us-east-1\nsource_profile=default\nrole_arn=$AwsCfServiceRoleArn" > ~/.aws/config
  - echo -e "[default]\nregion=us-east-1\naws_access_key_id=$AwsTravisAccessKey\naws_secret_access_key=$AwsTravisSecretAccessKey" > ~/.aws/credentials
stages:
  - name: validate
  - name: deploy
    if: (tag =~ ^[0-9]+\.[0-9]+\.[0-9]+) OR (branch = master AND type = push)
jobs:
  fast_finish: true
  include:
    - stage: validate
      script:
        - pipenv run pre-commit run --all-files
        - pipenv run sam build
        - pipenv run python -m pytest tests/ -v
    - stage: deploy
      script:
        - pipenv run sam build
        - |
          pipenv run sam package --template-file .aws-sam/build/template.yaml \
            --s3-bucket $LAMBDA_BUCKET \
            --output-template-file .aws-sam/build/$REPO_NAME.yaml
        - pipenv run sam publish --template .aws-sam/build/$REPO_NAME.yaml
        - pipenv run aws s3 cp .aws-sam/build/$REPO_NAME.yaml s3://$CFN_BUCKET/$REPO_NAME/$TRAVIS_BRANCH/
