name: lambda-test

on:
  # This is a dispatched workflow to be called as a job in other workflows
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow
  workflow_call:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1

  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: pip install -U pipenv
      - run: pipenv sync --dev
      - run: pipenv run coverage run -m pytest tests/ -svv
      - run: pipenv run coverage lcov
      - name: upload coverage to coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: coverage.lcov
          fail-on-error: false

  sam-build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/sam-build
      - run: sam validate --lint --template .aws-sam/build/template.yaml
